### ISSUE TITLE
Make an ouija-archives channel

### ISSUE THREAD

**Issue by connorshea** [connorshea/ouija-bot#22]
Rather than pinning the message to a channel, which limits the number of archived messages to 50, send the output to an archives channel.

I'm not sure how I feel about this, but the current situation with a 50 pin limit sucks 🤔

**Comment by z64** [comment]
Yeah, a `#ouija-board` (a la `#starboard` :stuck_out_tongue_winking_eye:) is definitely the right solution here, and is exactly why things like pins aren't used for starboards. It's the only viable solution, and should be configurable.

I might suggest adding a table too - it would enable some fun things like recalling/quoting past readings into context of a conversation. If I'm reading the commit log right, you've switched to postgres - you could take advantage of its `array` column types to insert an array of participant IDs of whoever took part in reading a particular message.
